####################################################################################################
# +----------------------------------------------------------------------------------------------+ #
# |                       ___       __       __                         __                       | #
# |                      |__   /\  /__` \ / |__)  /\  |\ | |__/ | |\ | / _`                      | #
# |                      |___ /~~\ .__/  |  |  \ /~~\ | \| |  \ | | \| \__>                      | #
# |                                                                                              | #
# |                                   Made by: Kaotich00                                         | #
# |                                                                                              | #
# |  SOURCE CODE: https://github.com/ForgottenWorld/EasyRanking                                  | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #
####################################################################################################

# +----------------------------------------------------------------------------------------------+ #
# |                                                                                              | #
# |                                       STORAGE SETTINGS                                       | #
# |                                                                                              | #
# |                               Configure MySQL Storage Settings                               | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #

# Define the address and port for the database.
address: 'localhost:3306'

# The name of the database to store EasyRanking data in.
database: 'easyranking'

# Admin Credentials for the database.
username: 'username'
password: 'password'

