####################################################################################################
# +----------------------------------------------------------------------------------------------+ #
# |                       ___       __       __                         __                       | #
# |                      |__   /\  /__` \ / |__)  /\  |\ | |__/ | |\ | / _`                      | #
# |                      |___ /~~\ .__/  |  |  \ /~~\ | \| |  \ | | \| \__>                      | #
# |                                                                                              | #
# |                                   Made by: Kaotich00                                         | #
# |                                                                                              | #
# |  SOURCE CODE: https://github.com/ForgottenWorld/EasyRanking                                  | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #
####################################################################################################

# +----------------------------------------------------------------------------------------------+ #
# |                                                                                              | #
# |                                       STORAGE SETTINGS                                       | #
# |                                                                                              | #
# |                               Configure MySQL Storage Settings                               | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #

# Define the address and port for the database.
address: 'localhost:3306'

# The name of the database to store EasyRanking data in.
database: 'easyranking'

# Admin Credentials for the database.
username: 'username'
password: 'password'

# How frequently should the plugin
# save the boards data and user scores
# to the database in minutes (default: 10)
sync_frequency: 10

# +----------------------------------------------------------------------------------------------+ #
# |                                                                                              | #
# |                                       BOARDS SETTINGS                                        | #
# |                                                                                              | #
# |                               Configure Default Leaderboards                                 | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #

# MOB KILLED LEADERBOARD
# Please never ever change the leaderboard node name,
# unless you want very big trouble
mobKilled:
  # Wheter the leaderboard should be enabled or not (default: true)
  enabled: true
  # Define the amount of points given for each monster type
  # See here for a full reference: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
  values:
    CREEPER: 3
    ZOMBIE: 2

#PLAYER KILLED LEADERBOARD
# Please never ever change the leaderboard node name,
# unless you want very big trouble
playerKilled:
  enabled: true

#ECONOMY LEADERBOARD
# Please never ever change the leaderboard node name,
# unless you want very big trouble
economy:
  enabled: true

#ORES MINED LEADERBOARD
# Please never ever change the leaderboard node name,
# unless you want very big trouble
oresMined:
  enabled: true
  # Define the amount of points given for each ore type
  values:
    EMERALD_ORE: 10
    DIAMOND_ORE: 8
    LAPIS_ORE: 5
    GOLD_ORE: 5
    IRON_ORE: 3
    REDSTONE_ORE: 2
    COAL_ORE: 1
    NETHER_QUARTZ_ORE: 1