####################################################################################################
# +----------------------------------------------------------------------------------------------+ #
# |                       ___       __       __                         __                       | #
# |                      |__   /\  /__` \ / |__)  /\  |\ | |__/ | |\ | / _`                      | #
# |                      |___ /~~\ .__/  |  |  \ /~~\ | \| |  \ | | \| \__>                      | #
# |                                                                                              | #
# |                                   Made by: Kaotich00                                         | #
# |                                                                                              | #
# |  SOURCE CODE: https://github.com/ForgottenWorld/EasyRanking                                  | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #
####################################################################################################

# +----------------------------------------------------------------------------------------------+ #
# |                                                                                              | #
# |                                       STORAGE SETTINGS                                       | #
# |                                                                                              | #
# |                               Configure MySQL Storage Settings                               | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #

# Define the address and port for the database.
address: 'localhost:3306'

# The name of the database to store EasyRanking data in.
database: 'easyranking'

# Admin Credentials for the database.
username: 'username'
password: 'password'

# How frequently should the plugin
# save the boards data and user scores
# to the database in minutes (default: 10)
sync_frequency: 10

# Web page link
web_page_link: 'PUT_LINK_HERE'

# +----------------------------------------------------------------------------------------------+ #
# |                                                                                              | #
# |                                       BOARDS SETTINGS                                        | #
# |                                                                                              | #
# |                               Configure Default Leaderboards                                 | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #

# MOB KILLED LEADERBOARD
# Please never ever change the leaderboard node name,
# unless you want very big trouble
mobKilled:
  # Wheter the leaderboard should be enabled or not (default: true)
  enabled: true
  # allow mobs spawned from spawner
  # (default: true) restart is needed if u change this value
  allowSpawner: true
  # Define the amount of points given for each monster type
  # See here for a full reference: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
  values:

# PLAYER KILLED LEADERBOARD
# Please never ever change the leaderboard node name,
# unless you want very big trouble
playerKilled:
  enabled: true

# ECONOMY LEADERBOARD
# Please never ever change the leaderboard node name,
# unless you want very big trouble
economy:
  enabled: true
  # How frequently should the economy board
  # update user balance in minutes(default: 5)
  sync_frequency: 5

# ORES MINED LEADERBOARD
# Please never ever change the leaderboard node name,
# unless you want very big trouble
oresMined:
  enabled: true
  # Define the amount of points given for each ore type
  values:

# DUNGEONS COMPLETED LEADERBOARD
# Please never ever change the leaderboard node name,
# unless you want very big trouble
dungeons:
  enabled: true

# BOUNTY LEADERBOARD
# Please never ever change the leaderboard node name,
# unless you want very big trouble
bounties:
  enabled: true

# WOOD CUT LEADERBOARD
# Please never ever change the leaderboard node name,
# unless you want very big trouble
wood:
  enabled: true
  # Define the amount of points given for each wood type
  values:

# FARMING LEADERBOARD
# Please never ever change the leaderboard node name,
# unless you want very big trouble
farming:
  enabled: true
  # Define the amount of points given for each cultivation type
  values:

# FISHING LEADERBOARD
# Please never ever change the leaderboard node name,
# unless you want very big trouble
fishing:
  enabled: true
  # Define the amount of points given
  values:

# PLAYER DEATH LEADERBOARD
# Please never ever change the leaderboard node name,
# unless you want very big trouble
playerDeath:
  enabled: true
