####################################################################################################
# +----------------------------------------------------------------------------------------------+ #
# |                       ___       __       __                         __                       | #
# |                      |__   /\  /__` \ / |__)  /\  |\ | |__/ | |\ | / _`                      | #
# |                      |___ /~~\ .__/  |  |  \ /~~\ | \| |  \ | | \| \__>                      | #
# |                                                                                              | #
# |                                   Made by: Kaotich00                                         | #
# |                                                                                              | #
# |  SOURCE CODE: https://github.com/ForgottenWorld/EasyRanking                                  | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #
####################################################################################################

# +----------------------------------------------------------------------------------------------+ #
# |                                                                                              | #
# |                                       STORAGE SETTINGS                                       | #
# |                                                                                              | #
# |                               Configure MySQL Storage Settings                               | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #

# Define the address and port for the database.
address: 'localhost:3306'

# The name of the database to store EasyRanking data in.
database: 'easyranking'

# Admin Credentials for the database.
username: 'username'
password: 'password'

# How frequently should the plugin
# save the boards data and user scores
# to the database in minutes (default: 10)
sync_frequency: 10

# Web page link
web_page_link: 'PUT_LINK_HERE'

# +----------------------------------------------------------------------------------------------+ #
# |                                                                                              | #
# |                                       BOARDS SETTINGS                                        | #
# |                                                                                              | #
# |                               Configure Default Leaderboards                                 | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #

# MOB KILLED LEADERBOARD
# Please never ever change the leaderboard node name,
# unless you want very big trouble
mobKilled:
  # Wheter the leaderboard should be enabled or not (default: true)
  enabled: true
  # Define the amount of points given for each monster type
  # See here for a full reference: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
  values:
    #HOSTILE
    CREEPER: 5
    ZOMBIE: 2
    SKELETON: 3
    CAVE_SPIDER: 3
    ENDERMAN: 5
    GHAST: 4
    MAGMA_CUBE: 2
    PHANTOM: 2
    SLIME: 1
    WITCH: 3
    SPIDER: 2

# PLAYER KILLED LEADERBOARD
# Please never ever change the leaderboard node name,
# unless you want very big trouble
playerKilled:
  enabled: true

# ECONOMY LEADERBOARD
# Please never ever change the leaderboard node name,
# unless you want very big trouble
economy:
  enabled: true
  # How frequently should the economy board
  # update user balance in minutes(default: 5)
  sync_frequency: 5

# ORES MINED LEADERBOARD
# Please never ever change the leaderboard node name,
# unless you want very big trouble
oresMined:
  enabled: true
  # Define the amount of points given for each ore type
  values:
    ANCIENT_DEBRIS: 20
    EMERALD_ORE: 10
    DIAMOND_ORE: 20
    LAPIS_ORE: 5
    GOLD_ORE: 5
    IRON_ORE: 3
    COPPER_ORE: 3
    REDSTONE_ORE: 2
    COAL_ORE: 1
    NETHER_QUARTZ_ORE: 1
    NETHER_GOLD_ORE: 5

# DUNGEONS COMPLETED LEADERBOARD
# Please never ever change the leaderboard node name,
# unless you want very big trouble
dungeons:
  enabled: true

# BOUNTY LEADERBOARD
# Please never ever change the leaderboard node name,
# unless you want very big trouble
bounties:
  enabled: true

# WOOD CUT LEADERBOARD
# Please never ever change the leaderboard node name,
# unless you want very big trouble
wood:
  enabled: true
  # Define the amount of points given for each wood type
  values:
    BIRCH_LOG: 1
    SPRUCE_LOG: 1
    OAK_LOG: 1
    JUNGLE_LOG: 1
    ACACIA_LOG: 1
    DARK_OAK_LOG: 1
    CRIMSON_HYPHAE: 1
    WARPED_HYPHAE: 1

# FARMING LEADERBOARD
# Please never ever change the leaderboard node name,
# unless you want very big trouble
farming:
  enabled: true
  # Define the amount of points given for each cultivation type
  values:
    WHEAT: 3
    CARROTS: 3
    POTATOES: 3
    BEETROOTS: 3
    COCOA: 3
    NETHER_WART: 3
    SWEET_BERRY_BUSH: 2
    MELON: 2
    PUMPKIN: 2
    RED_MUSHROOM: 1
    BROWN_MUSHROOM: 1
    CRIMSON_FUNGUS: 1
    WARPED_FUNGUS: 1
    SUGAR_CANE: 1
    CACTUS: 1
    BAMBOO: 1

# FISHING LEADERBOARD
# Please never ever change the leaderboard node name,
# unless you want very big trouble
fishing:
  enabled: true
  # Define the amount of points given
  values:
    COD: 1
    SALMON: 1
    PUFFERFISH: 5
    ENCHANTED_BOOK: 20
    TROPICAL_FISH: 10
    NAUTILUS_SHELL: 2
    SADDLE: 5

# PLAYER DEATH LEADERBOARD
# Please never ever change the leaderboard node name,
# unless you want very big trouble
playerDeath:
  enabled: true
