name: Easyranking
version: ${project.version}
main: me.kaotich00.easyranking.Easyranking
api-version: 1.13
authors: [Kaotich00]
description: A simple and lightweight plugin for custom Ranking Systems
depend: [Vault]
softdepend: [PlaceholderAPI,Bounties]
loadafter: [Vault,PlaceholderAPI,Bounties]
commands:
  er:
    description: Main EasyRanking command
    usage: /<command>
    aliases: [er, easy, easyranking]